new GSoC idea for license submission tool
spdx/GSoC pull request #5
Opened 2023-02-01 23:21 UTC by jlovejoy

I need to add more to this, but it's a start

need input from @swinslow and @goneall as well!

2023-02-02 22:46 UTC, zvr requested changes

2023-02-02 22:46 UTC, zvr commented on 2023_ideas.md
> +
Can we also add a pointer to the source of the current tool? @goneall can you provide this?

2023-02-02 22:46 UTC, zvr commented on 2023_ideas.md
> +not sure...
From the description of the changes to the current tool, it looks to me like a medium-size project (around 175 hours).

2023-02-03 14:47 UTC, goneall requested changes
Just a few suggestions and additions

2023-02-03 14:47 UTC, goneall commented on 2023_ideas.md
> +* ??
Couple of ideas:
- Add support for exceptions
- Add or fix unit tests
- Improve the error handling, especially when Github pull requests fail

2023-02-03 14:47 UTC, goneall commented on 2023_ideas.md
> +* ??
What do you think about adding https://github.com/spdx/spdx-online-tools/issues/398?

2023-02-03 14:47 UTC, goneall commented on 2023_ideas.md
> +not sure...
Agree - medium project

2023-02-03 14:47 UTC, goneall commented on 2023_ideas.md
> +
Here's some more links:

- https://github.com/spdx/spdx-online-tools - repo
- https://github.com/spdx/spdx-online-tools/issues/399 - issue to add .txt file
- https://github.com/spdx/spdx-online-tools/issues/398 - exceptions to be added

2023-02-04 12:12 UTC, zvr commented
We can also add a generic text "Various improvements on the tool are documented as GitHub tickets tagged `Submit New License` https://github.com/spdx/spdx-online-tools/issues?q=is%3Aissue+is%3Aopen+label%3A%22Submit+New+License%22"

2023-02-06 20:48 UTC, jlovejoy commented
Thanks @goneall and @zvr - I think I've updated to address your suggestions!

2023-02-07 17:58 UTC, zvr commented
@jlovejoy can you rebase on the latest version already published? Your changes are still from the older version and therefore present "conflicts" (on the box here), so that merging is blocked.

2023-02-07 21:00 UTC, jlovejoy commented
ugh, I don't now how to resolve conflicts...

2023-02-07 22:57 UTC, merged